### ISSUE TITLE
I want to know something.

### ISSUE THREAD

**Issue by ghost** [lzls/SlidingDrawerLayout#1]
If I have a textview on end drawer how to change it's text manually. Because when I am using findview...then setText it's always returning null object reference. Can you provide me the exact process or this is the right process.
#TIA

**Comment by lzls** [comment]
You can get the end drawer reference in any method of the `OnDrawerScrollListener` if you used a ViewStub to wrap it, and then use its findViewById to find the TextView you need set text for. In this case, the end drawer is inflated and added to the view tree the first time it is to be opened.
